### ISSUE TITLE
feat: support a `--trace` or `--debug` flag

### ISSUE THREAD

**Issue by osterman** [mumoshu/variant2#11]
## what
* provide a way to trace the execution of a pipeline with verbose output of what's being run and the values of options and parameters (perhaps mask secrets?)

## use-case
* The more complicated the executions, the harder it is to debug what's going on
* Perhaps it would be also helpful to be able to step through the execution (but this is not immediately a requirement for me)

**Comment by mumoshu** [comment]
@osterman Hey! Thanks for this - Please read https://github.com/mumoshu/variant2#debugging-commands to see how it works. I've chosen the envvar to enable tracing, so that we don't pollute user defined `variant run` flags.

**Comment by osterman** [comment]
Make sense. Thanks!!
