### ISSUE TITLE
Feature Request: Support Variables in `config { .... }` and multiple configs for deep merging in a single source

### ISSUE THREAD

**Issue by osterman** [mumoshu/variant2#42]
##  what
- support variables in config {....} block
- support multiple `files` passed to `source`

## why
- Make it easy to pass a list of YAML configurations that get deep merged

## use-case
- We define a `import` directive in our [atmos cli configuration](https://github.com/cloudposse/atmos#centralized-project-configuration) that we use to layer configurations on top of each other
- We need this in order to support this behavior

**Comment by mumoshu** [comment]
@osterman This sounds like a great addition!

I've released v0.37.0 for this initial attempt to support this, which should be available within a few minutes. Please try and don't hesitate to leave any feedback/requests.
