### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by hugo-ninja** [mumoshu/variant2#53]
Have the variants2 commands changed?

Trying to follow the getting started but the run and export commands are missing all i see is:

Usage:
  variant [command]

Available Commands:
  build       Create a single executable from the Variantfile
  env         Print currently selected environment
  help        Help about any command
  init        Create a Variant command
  utils       Create a Variant command
  version     Print the version number of this command

When trying to run a build of the getting started im getting the following error:

Unexpected type of error *errors.withStack: yaml.Unmarshal failed: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `option ...` into map[string]interface {}: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `option ...` into map[string]interface {

**Comment by mumoshu** [comment]
@hugo-ninja You seem to be running the first version of variant (not variant2)!
