### ISSUE TITLE
Support Interactive Commands

### ISSUE THREAD

**Issue by osterman** [mumoshu/variant2#9]
## what
* Running variant with interactive commands fails
* I believe the original variant supported this mode

## use-case

Terraform apply can be run interactively on the console. While this is not the primary workflow, especially with gitops, during testing this is nice to "slow things down" and not make any mistakes.

## example

First run `touch /tmp/test`, then create a script with the following and run the `example` job. 

```
#!/usr/bin/env variant

job "example" {
  description = "interactive test"
  exec {
      command = "rm"
      args = [ "-i", "/tmp/test" ]
   }
}
```

**Comment by mumoshu** [comment]
Implemented in https://github.com/mumoshu/variant2/commit/94a6ff9f72a97c6bee6e0df16254c540f5b616cb and available since v0.21.0. Thanks for the feedback and the request, @osterman!
